In [24]:
import pandas as pd
# pour la recherche d'un chemin particulier correspondant à un motif indique dans le chemin
import glob
path = r'C:\Users\rabi3\Desktop\scraping\corpus_sidata\youtube' # use your path
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename,  sep = ';',index_col=None, header=0)
    li.append(df)

df_youtube= pd.concat(li, axis=0, ignore_index=True)

# choisir les attributs de travail

df_youtube1=df_youtube[['comment','like']]
### la même chose pour twitter

import pandas as pd
# pour la recherche d'un chemin particulier correspondant à un motif indique dans le chemin
import glob
path = r'C:\Users\rabi3\Desktop\scraping\corpus_sidata\twitter' # use your path
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename,  sep = ';',index_col=None, header=0)
    li.append(df)

df_twitter= pd.concat(li, axis=0, ignore_index=True)

# choisir les attributs de travail

df_twitter1=df_twitter[['text','like']]

### la même chose pour google play

import pandas as pd
# pour la recherche d'un chemin particulier correspondant à un motif indique dans le chemin
import glob
path = r'C:\Users\rabi3\Desktop\scraping\corpus_sidata\googleplay' # use your path
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename,  sep = ';',index_col=None, header=0)
    li.append(df)

df_googleplay= pd.concat(li, axis=0, ignore_index=True)

# .............
df_googleplay=df_googleplay[['text','score']]


#### ....................................

df_googleplay.columns = ['comment','like']
df_twitter1.columns = ['comment','like']
df_youtube1.columns = ['comment','like']
print(df_googleplay)

   comment  like
0       jh    56
1       ml    24
2  bonjour    34
3    hello    23

In [23]:
frame = [df_googleplay, df_twitter1, df_youtube1]
keys1=["youtube", "googleplay", "twitter"]
result = pd.concat(frame, keys=keys1)
# result.iloc[0]
result

              comment  like
youtube    0       jh    56
           1       ml    24
           2  bonjour    34
           3    hello    23
googleplay 0       jh    56
           1       ml    24
           2  bonjour    34
           3    hello    23
twitter    0       jh    56
           1       ml    24
           2  bonjour    34
           3    hello    23